name: Bug Report
description: Report a problem with Selenium.HarCapture
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug. Please fill in as much detail as possible so the issue can be reproduced and fixed quickly.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the behavior.
      placeholder: |
        1. Start HAR capture with ...
        2. Navigate to ...
        3. Stop capture and call GetHar() ...
        4. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: input
    id: package-version
    attributes:
      label: Package version
      placeholder: "0.3.1"
    validations:
      required: true

  - type: dropdown
    id: capture-strategy
    attributes:
      label: Capture strategy
      description: Which capture strategy are you using?
      options:
        - CDP (default)
        - INetwork (ForceSeleniumNetwork)
        - Unknown
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Operating system, .NET version, Chrome version.
      placeholder: "OS: Windows 11 / macOS 15 / Ubuntu 24.04, .NET: 9.0.x, Chrome: 132.x"
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other context, stack traces, or HAR snippets that might help.
    validations:
      required: false
